# Generated by Django 3.0.8 on 2020-07-31 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmanifest',
            name='context',
            field=models.ForeignKey(blank=True, db_column='context_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest'),
        ),
        migrations.AlterField(
            model_name='allmanifest',
            name='item_class',
            field=models.ForeignKey(db_column='item_class_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest'),
        ),
        migrations.AlterField(
            model_name='allmanifest',
            name='project',
            field=models.ForeignKey(db_column='project_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest'),
        ),
        migrations.AlterField(
            model_name='allmanifest',
            name='published',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='allmanifest',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest'),
        ),
        migrations.AlterField(
            model_name='allmanifest',
            name='revised',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
