# Generated by Django 3.0.8 on 2020-10-20 18:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('field_count', models.IntegerField()),
                ('row_count', models.IntegerField()),
                ('source_type', models.TextField()),
                ('is_current', models.BooleanField(default=None)),
                ('status', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('project', models.ForeignKey(db_column='project_uuid', default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', default='aa88bc27-e082-44b5-b51b-73a3f268f939', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'etl_sources',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceField',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('field_num', models.IntegerField()),
                ('label', models.TextField()),
                ('ref_name', models.TextField(null=True)),
                ('ref_orig_name', models.TextField(null=True)),
                ('item_type', models.TextField(null=True)),
                ('data_type', models.TextField(null=True)),
                ('value_prefix', models.TextField(null=True)),
                ('unique_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('data_source', models.ForeignKey(db_column='source_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSource')),
                ('item_class', models.ForeignKey(db_column='item_class_uuid', default='00000000-0000-0000-0000-000000000002', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'etl_fields',
                'ordering': ['data_source', 'field_num'],
                'unique_together': {('data_source', 'field_num')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceRecord',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('row_num', models.IntegerField()),
                ('field_num', models.IntegerField()),
                ('record', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(db_column='context_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('data_source', models.ForeignKey(db_column='source_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSource')),
                ('item', models.ForeignKey(db_column='item_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'etl_records',
                'ordering': ['data_source', 'row_num', 'field_num'],
                'unique_together': {('data_source', 'row_num', 'field_num')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceAnnotation',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('obj_string_hash', models.TextField(null=True)),
                ('obj_string', models.TextField(null=True)),
                ('obj_boolean', models.BooleanField(null=True)),
                ('obj_integer', models.BigIntegerField(null=True)),
                ('obj_double', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('obj_datetime', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('attribute_group', models.ForeignKey(db_column='attribute_group_uuid', default='00000000-0000-0000-0000-000000000005', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('attribute_group_field', models.ForeignKey(db_column='attribute_group_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('data_source', models.ForeignKey(db_column='source_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSource')),
                ('event', models.ForeignKey(db_column='event_uuid', default='00000000-0000-0000-0000-000000000004', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('event_field', models.ForeignKey(db_column='event_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('language', models.ForeignKey(db_column='language_uuid', default='00000000-75e9-d759-8d1d-eaa07c1c03dc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('language_field', models.ForeignKey(db_column='language_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('object', models.ForeignKey(db_column='object_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('object_field', models.ForeignKey(db_column='object_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('observation', models.ForeignKey(db_column='observation_uuid', default='00000000-0000-0000-0000-000000000003', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('observation_field', models.ForeignKey(db_column='observation_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('predicate', models.ForeignKey(db_column='predicate_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('predicate_field', models.ForeignKey(db_column='predicate_field_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
                ('subject_field', models.ForeignKey(db_column='subject_field_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='importer.DataSourceField')),
            ],
            options={
                'db_table': 'etl_annotations',
                'ordering': ['data_source', 'subject_field'],
                'unique_together': {('data_source', 'subject_field', 'predicate', 'predicate_field', 'object', 'object_field', 'obj_string_hash', 'obj_boolean', 'obj_integer', 'obj_double', 'obj_datetime', 'language', 'language_field')},
            },
        ),
    ]
