# Generated by Django 3.0.8 on 2020-07-31 21:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllManifest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(default='id', max_length=50)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('sort', models.SlugField(max_length=70)),
                ('views', models.IntegerField()),
                ('indexed', models.DateTimeField(blank=True, null=True)),
                ('vcontrol', models.DateTimeField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(db_index=True)),
                ('revised', models.DateTimeField(db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(max_length=300, unique=True)),
                ('item_key', models.CharField(blank=True, max_length=300, null=True)),
                ('identifiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('hash_id', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('context', models.ForeignKey(blank=True, db_column='context_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('item_class', models.ForeignKey(db_column='item_class_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('project', models.ForeignKey(db_column='project_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'oc_all_manifest',
                'unique_together': {('item_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AllString',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hash_id', models.CharField(max_length=50, unique=True)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'oc_all_strings',
            },
        ),
        migrations.CreateModel(
            name='AllHistory',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('hash_item', models.CharField(max_length=50, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('subject', models.ForeignKey(db_column='subject_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'oc_all_history',
            },
        ),
        migrations.CreateModel(
            name='AllAssertion',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('obs_sort', models.IntegerField()),
                ('attribute_group_sort', models.IntegerField()),
                ('sort', models.DecimalField(decimal_places=3, max_digits=8)),
                ('visible', models.BooleanField(default=True)),
                ('certainty', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('obj_boolean', models.BooleanField(blank=True, null=True)),
                ('obj_integer', models.BigIntegerField(blank=True, null=True)),
                ('obj_double', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('obj_datetime', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('attribute_group', models.ForeignKey(db_column='attribute_group_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('obj_string', models.ForeignKey(blank=True, db_column='obj_string_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllString')),
                ('object', models.ForeignKey(blank=True, db_column='object_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('observation', models.ForeignKey(db_column='observation_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('predicate', models.ForeignKey(db_column='predicate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.AllManifest')),
                ('project', models.ForeignKey(db_column='project_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.AllManifest')),
                ('subject', models.ForeignKey(db_column='subject_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='subject_uuid', to='all_items.AllManifest')),
            ],
            options={
                'db_table': 'oc_all_assertions',
                'unique_together': {('subject', 'observation', 'attribute_group', 'predicate', 'object', 'obj_string', 'obj_boolean', 'obj_integer', 'obj_double', 'obj_datetime')},
            },
        ),
    ]
