# Generated by Django 5.1 on 2025-07-16 22:13

import django.db.models.deletion
from django.db import migrations, models


"""
# Indexes for the AllAssertion model

CREATE INDEX "oc_all_manifest_item_type_7a1264f2" ON "oc_all_manifest" ("item_type");
CREATE INDEX "oc_all_manifest_item_type_7a1264f2_like" ON "oc_all_manifest" ("item_type" text_pattern_ops);

CREATE INDEX "subject_visible_idx" ON "oc_all_assertions" ("subject_uuid", "visible");
CREATE INDEX "subject_predicate_visible_idx" ON "oc_all_assertions" ("subject_uuid", "predicate_uuid", "visible");
CREATE INDEX "subject_object_visible_idx" ON "oc_all_assertions" ("subject_uuid", "object_uuid", "visible");
CREATE INDEX "predicate_visible_idx" ON "oc_all_assertions" ("predicate_uuid", "visible");
CREATE INDEX "object_visible_idx" ON "oc_all_assertions" ("object_uuid", "visible");

"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllManifest',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(db_index=True)),
                ('item_type', models.TextField(db_index=True)),
                ('data_type', models.TextField(default='id')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('label', models.TextField()),
                ('sort', models.SlugField(max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('indexed', models.DateTimeField(blank=True, null=True)),
                ('vcontrol', models.DateTimeField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(db_index=True, null=True)),
                ('revised', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uri', models.TextField(unique=True)),
                ('item_key', models.TextField(blank=True, null=True)),
                ('hash_id', models.TextField(unique=True)),
                ('path', models.TextField(blank=True, db_index=True, null=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('context', models.ForeignKey(blank=True, db_column='context_uuid', default='00000000-0000-0000-0000-000000000001', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
                ('item_class', models.ForeignKey(db_column='item_class_uuid', default='00000000-0000-0000-0000-000000000002', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
                ('project', models.ForeignKey(db_column='project_uuid', default='00000000-0000-0000-0000-000000000001', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', default='aa88bc27-e082-44b5-b51b-73a3f268f939', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_manifest',
                'default_related_name': 'manifests',
            },
        ),
        migrations.CreateModel(
            name='AllHistory',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('sha1_hash', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('item', models.ForeignKey(db_column='item_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_history',
                'ordering': ['item', 'updated'],
                'default_related_name': 'histories',
            },
        ),
        migrations.CreateModel(
            name='AllIdentifier',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('scheme', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('item', models.ForeignKey(db_column='item_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_identifiers',
                'ordering': ['item', 'rank', 'scheme'],
                'default_related_name': 'identifiers',
                'unique_together': {('item', 'scheme', 'rank'), ('scheme', 'id')},
            },
        ),
        migrations.CreateModel(
            name='AllAssertion',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(db_index=True)),
                ('obs_sort', models.IntegerField(default=1)),
                ('event_sort', models.IntegerField(default=1)),
                ('attribute_group_sort', models.IntegerField(default=1)),
                ('sort', models.FloatField(default=1, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('certainty', models.FloatField(null=True)),
                ('obj_string_hash', models.TextField()),
                ('obj_string', models.TextField(null=True)),
                ('obj_boolean', models.BooleanField(null=True)),
                ('obj_integer', models.BigIntegerField(null=True)),
                ('obj_double', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('obj_datetime', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('attribute_group', models.ForeignKey(db_column='attribute_group_uuid', default='00000000-0000-0000-0000-000000000005', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('event', models.ForeignKey(db_column='event_uuid', default='00000000-0000-0000-0000-000000000004', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('language', models.ForeignKey(db_column='language_uuid', default='00000000-75e9-d759-8d1d-eaa07c1c03dc', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('object', models.ForeignKey(db_column='object_uuid', default='00000000-0000-0000-0000-000000000006', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
                ('observation', models.ForeignKey(db_column='observation_uuid', default='00000000-0000-0000-0000-000000000003', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('predicate', models.ForeignKey(db_column='predicate_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='all_items.allmanifest')),
                ('project', models.ForeignKey(db_column='project_uuid', default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', default='aa88bc27-e082-44b5-b51b-73a3f268f939', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('subject', models.ForeignKey(db_column='subject_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='subject_uuid', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_assertions',
                'ordering': ['subject', 'obs_sort', 'event_sort', 'attribute_group_sort', 'sort'],
                'default_related_name': 'assertions',
                'indexes': [models.Index(fields=['subject', 'visible'], name='subject_visible_idx'), models.Index(fields=['subject', 'predicate', 'visible'], name='subject_predicate_visible_idx'), models.Index(fields=['subject', 'object', 'visible'], name='subject_object_visible_idx'), models.Index(fields=['predicate', 'visible'], name='predicate_visible_idx'), models.Index(fields=['object', 'visible'], name='object_visible_idx')],
                'unique_together': {('subject', 'observation', 'event', 'attribute_group', 'predicate', 'object', 'language', 'obj_string_hash', 'obj_boolean', 'obj_integer', 'obj_double', 'obj_datetime')},
            },
        ),
        migrations.CreateModel(
            name='AllResource',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(db_index=True)),
                ('uri', models.TextField()),
                ('sha256_checksum', models.TextField(null=True)),
                ('filesize', models.DecimalField(decimal_places=3, max_digits=19, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('is_static', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('item', models.ForeignKey(db_column='item_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('mediatype', models.ForeignKey(db_column='mediatype_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('project', models.ForeignKey(db_column='project_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('resourcetype', models.ForeignKey(db_column='resourcetype_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_resources',
                'ordering': ['item', 'rank', 'resourcetype'],
                'default_related_name': 'resources',
                'unique_together': {('item', 'resourcetype', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='AllSpaceTime',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(db_index=True)),
                ('feature_id', models.IntegerField(default=1)),
                ('earliest', models.DecimalField(decimal_places=5, max_digits=19, null=True)),
                ('start', models.DecimalField(decimal_places=5, max_digits=19, null=True)),
                ('stop', models.DecimalField(decimal_places=5, max_digits=19, null=True)),
                ('latest', models.DecimalField(decimal_places=5, max_digits=19, null=True)),
                ('geometry_type', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=21, max_digits=24, null=True)),
                ('longitude', models.DecimalField(decimal_places=21, max_digits=24, null=True)),
                ('geo_specificity', models.IntegerField(default=0, null=True)),
                ('geometry', models.JSONField(default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
                ('event', models.ForeignKey(db_column='event_uuid', default='00000000-0000-0000-0000-000000000004', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('item', models.ForeignKey(db_column='item_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='item_uuid', to='all_items.allmanifest')),
                ('project', models.ForeignKey(db_column='project_uuid', default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
                ('publisher', models.ForeignKey(db_column='publisher_uuid', default='aa88bc27-e082-44b5-b51b-73a3f268f939', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='all_items.allmanifest')),
            ],
            options={
                'db_table': 'oc_all_spacetime',
                'ordering': ['item', 'feature_id'],
                'default_related_name': 'spacetimes',
                'unique_together': {('item', 'event'), ('item', 'feature_id')},
            },
        ),
    ]
