# Generated by Django 3.2.9 on 2021-11-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allspacetime',
            name='event_class',
        ),
    ]
