
import uuid as GenUUID

from opencontext_py.apps.all_items.configs import *
from opencontext_py.apps.all_items.models import (
    AllManifest,
    AllString,
    AllAssertion,
    AllHistory,
)

"""
from opencontext_py.apps.all_items.defaults import (
    load_default_entities,
    verify_manifest_uuids,
)
verify_manifest_uuids()
load_default_entities()

"""

DEFAULT_STRINGS = [
    {
        'uuid': DEFAULT_NULL_STRING_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'content': '',
    },
]


# These items are fundamental to load into the database as Manifest items
# for Open Context to work at all.
DEFAULT_MANIFESTS = [
    # Root Open Context entities
    {
        'uuid': OPEN_CONTEXT_PROJ_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'projects',
        'data_type': 'id',
        'slug': 'open-context',
        'label': 'Open Context',
        'uri': 'opecontext.org/projects/open-context',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
        'identifiers': ['0'],
        'meta_json': {
            'short_id': 0,
        }
    },
    {
        'uuid': OPEN_CONTEXT_PUB_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'open-context-org',
        'label': 'Open Context: Publishing research data on the Web',
        'uri': 'opecontext.org',
    },
    {
        'uuid': OC_GEN_VOCAB_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'oc-general',
        'label': 'Open Context Concepts',
        'uri': 'opencontext.org/vocabularies/oc-general',
        'item_key': 'oc-gen',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
        'identifiers': [
            'https://raw.githubusercontent.com/ekansa/oc-ontologies/master/vocabularies/oc-general.owl'
        ],
    },
    # Default Open Context Class
    {
        'uuid': DEFAULT_CLASS_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'oc-default-class',
        'label': 'Default (null) class',
        'uri': 'opencontext.org/vocabularies/oc-general/default-class',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    # Additional Open Context vocabularies
    {
        'uuid': DINAA_VOCAB_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'dinaa',
        'label': 'Digital Index of North American Archaeology (DINAA) Vocabulary',
        'uri': 'http://opencontext.org/vocabularies/dinaa',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
        'identifiers': [
            'https://raw.githubusercontent.com/ekansa/oc-ontologies/master/vocabularies/dinaa-alt.owl'
        ],
    },
    {
        'uuid': OCZOO_VOCAB_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'oc-zoo',
        'label': 'Open Context Zooarchaeology Annotations',
        'uri': 'http://opencontext.org/vocabularies/open-context-zooarch',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
        'identifiers': [
            'https://raw.githubusercontent.com/ekansa/oc-ontologies/master/vocabularies/zooarchaeology-alt.owl'
        ],
    },
    # Default Open Context Assertion Node entities
    {
        'uuid': DEFAULT_OBS_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'observations',
        'data_type': 'id',
        'slug': 'oc-default-obs',
        'label': 'Main Observation',
        'uri': 'opencontext.org/vocabularies/oc-general/observations#obs-1',
        'item_key': '#obs-1',
        'context_id': OC_GEN_VOCAB_UUID,
        'meta_json': {
            'sort': 1,
        }
    },
    {
        'uuid': DEFAULT_EVENT_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'events',
        'data_type': 'id',
        'slug': 'oc-default-event',
        'label': 'Default Event',
        'uri': 'opencontext.org/vocabularies/oc-general/events#event-1',
        'item_key': '#event-1',
        'context_id': OC_GEN_VOCAB_UUID,
        'meta_json': {
            'sort': 1,
        }
    },
    {
        'uuid': DEFAULT_ATTRIBUTE_GROUP_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'attribute-groups',
        'data_type': 'id',
        'slug': 'oc-default-attrib-group',
        'label': 'Default (Single) Attribute Group',
        'uri': 'opencontext.org/vocabularies/oc-general/attribute-group#group-1',
        'context_id': OC_GEN_VOCAB_UUID,
        'meta_json': {
            'sort': 1,
        }
    },
    {
        'uuid': DEFAULT_NULL_OBJECT_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'types',
        'data_type': 'id',
        'slug': 'oc-default-object-null',
        'label': 'Default (Null) Attribute Object',
        'uri': 'opencontext.org/vocabularies/oc-general/object-null',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    # Open Context hard-coded, widely used predicates
    {
        'uuid': PREDICATE_PROJ_ROOT_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'id',
        'slug': 'oc-gen-contains-root',
        'label': 'Default Project Root',
        'item_key': 'oc-gen:contains-root',
        'uri': 'opencontext.org/vocabularies/oc-general/contains-root',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_CONTAINS_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'id',
        'slug': 'oc-gen-contains',
        'label': 'Contains (spatial context)',
        'item_key': 'oc-gen:contains',
        'uri': 'opencontext.org/vocabularies/oc-general/contains',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_LINK_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'id',
        'slug': 'oc-gen-links',
        'label': 'Links',
        'item_key': 'oc-gen:links',
        'uri': 'opencontext.org/vocabularies/oc-general/links',
        'identifiers': [
            'oc-3',
        ],
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_NOTE_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'xsd:string',
        'slug': 'oc-gen-has-note',
        'label': 'Has note',
        'item_key': 'oc-gen:has-note',
        'uri': 'opencontext.org/vocabularies/oc-general/has-note',
    },
    {
        'uuid': PREDICATE_LINKED_FROM_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'id',
        'slug': 'oc-gen-is-linked-from',
        'label': 'Is Linked From',
        'item_key': 'oc-gen:is-linked-from',
        'uri': 'opencontext.org/vocabularies/oc-general/is-linked-from',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_GEO_OVERLAY_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'predicates',
        'data_type': 'id',
        'slug': 'oc-gen-has-geo-overlay',
        'label': 'Has geographic overlay',
        'item_key': 'oc-gen:has-geo-overlay',
        'uri': 'opencontext.org/vocabularies/oc-general/has-geo-overlay',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_OC_HAS_ICON_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'oc-gen-has-icon',
        'label': 'Has icon',
        'item_key': 'oc-gen:hasIcon',
        'uri': 'opencontext.org/vocabularies/oc-general/hasIcon',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_OC_HAS_TECHNIQUE_UUID,
        'publisher_id': OPEN_CONTEXT_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'oc-gen-has-technique',
        'label': 'Has technique',
        'item_key': 'oc-gen:has-technique',
        'uri': 'opencontext.org/vocabularies/oc-general/has-technique',
        'context_id': OC_GEN_VOCAB_UUID,
    },
    # W3C publisher and vocabularies
    {
        'uuid': W3C_PUB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'w3c',
        'label': 'World Wide Web Consortium (W3C)',
        'uri': 'https://www.w3.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': RDF_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'rdf',
        'label': 'The RDF Concepts Vocabulary (RDF)',
        'uri': 'https://www.w3.org/1999/02/22-rdf-syntax-ns',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': RDFS_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'rdfs',
        'label': 'The RDF Schema vocabulary (RDFS)',
        'uri': 'https://www.w3.org/2000/01/rdf-schema',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': XSD_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'xsd',
        'label': 'XML Schema',
        'uri': 'https://www.w3.org/2001/XMLSchema',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': SKOS_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'skos',
        'label': 'Simple Knowledge Organization System (SKOS)',
        'uri': 'http://www.w3.org/2004/02/skos/core',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': OWL_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'owl',
        'label': 'The OWL 2 Schema vocabulary (OWL 2)',
        'uri': 'https://www.w3.org/2002/07/owl',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': DCAT_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'dcat',
        'label': 'Data Catalog Vocabulary (DCAT) Version 2',
        'uri': 'https://www.w3.org/ns/dcat#',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': WEB_GEO_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'wgs84-geo',
        'label': 'Basic Geo (WGS84 lat/long) Vocabulary',
        'uri': 'www.w3.org/2003/01/geo/wgs84_pos',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': VOID_VOCAB_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'void-vocab',
        'label': 'Vocabulary of Interlinked Datasets (VoID)',
        'uri': 'https://www.w3.org/TR/void/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': PREDICATE_VOID_DATADUMP_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'void-data-dump',
        'label': 'RDF dump of a dataset',
        'item_key': 'void:dataDump',
        'uri': 'http://rdfs.org/ns/void#dataDump',
        'context_id': VOID_VOCAB_UUID,
    },
    # DCMI / Dublin Core publisher and vocabularies
    {
        'uuid': DCMI_PUB_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'dcmi',
        'label': 'Dublin Core Metadata Initiative (DCMI)',
        'uri': 'https://dublincore.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': DCTERMS_VOCAB_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'dc-terms',
        'label': 'DCMI Metadata Terms (Dublin Core Terms)',
        'uri': 'http://purl.org/dc/terms/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': DCMI_VOCAB_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'dcmi-terms',
        'label': 'DCMI Metadata Terms (Dublin Core Elements)',
        'uri': 'http://dublincore.org/documents/dcmi-terms/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_ABSTRACT_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-abstract',
        'label': 'Abstract',
        'item_key': 'dc-terms:abstract',
        'uri': 'http://purl.org/dc/terms/abstract',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_BIBLIO_CITE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-bibliographic-citation',
        'label': 'Bibliographic Citation',
        'item_key': 'dc-terms:bibliographicCitation',
        'uri': 'http://purl.org/dc/terms/bibliographicCitation',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_CREATED_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:date',
        'slug': 'dc-terms-created',
        'label': 'Date Created',
        'item_key': 'dc-terms:created',
        'uri': 'http://purl.org/dc/terms/created',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_DATE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:date',
        'slug': 'dc-terms-date',
        'label': 'Date',
        'item_key': 'dc-terms:date',
        'uri': 'http://purl.org/dc/terms/date',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_DESCRIPTION_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-description',
        'label': 'Description',
        'item_key': 'dc-terms:description',
        'uri': 'http://purl.org/dc/terms/description',
        'context_id': DCTERMS_VOCAB_UUID,
    },
     {
        'uuid': PREDICATE_DCTERMS_IDENTIFIER_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-identifier',
        'label': 'Identifier',
        'item_key': 'dc-terms:identifier',
        'uri': 'http://purl.org/dc/terms/identifier',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_ISSUED_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:date',
        'slug': 'dc-terms-issued',
        'label': 'Date Issued',
        'item_key': 'dc-terms:issued',
        'uri': 'http://purl.org/dc/terms/issued',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_MODIFIED_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:date',
        'slug': 'dc-terms-modified',
        'label': 'Date Modified',
        'item_key': 'dc-terms:modified',
        'uri': 'http://purl.org/dc/terms/modified',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_PROVENANCE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-provenance',
        'label': 'Provenance',
        'item_key': 'dc-terms:provenance',
        'uri': 'http://purl.org/dc/terms/provenance',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_TITLE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'dc-terms-title',
        'label': 'Title',
        'item_key': 'dc-terms:title',
        'uri': 'http://purl.org/dc/terms/title',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_CONTRIBUTOR_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-contributor',
        'label': 'Contributor',
        'item_key': 'dc-terms:contributor',
        'uri': 'http://purl.org/dc/terms/contributor',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_CREATOR_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-creator',
        'label': 'Creator',
        'item_key': 'dc-terms:creator',
        'uri': 'http://purl.org/dc/terms/creator',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_COVERAGE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-coverage',
        'label': 'Coverage',
        'item_key': 'dc-terms:coverage',
        'uri': 'http://purl.org/dc/terms/coverage',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_FORMAT_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-format',
        'label': 'Format',
        'item_key': 'dc-terms:format',
        'uri': 'http://purl.org/dc/terms/format',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_HAS_FORMAT_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-has-format',
        'label': 'Has Format',
        'item_key': 'dc-terms:hasFormat',
        'uri': 'http://purl.org/dc/terms/hasFormat',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_HAS_PART_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-has-part',
        'label': 'Has Part',
        'item_key': 'dc-terms:hasPart',
        'uri': 'http://purl.org/dc/terms/hasPart',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_HAS_VERSION_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-has-version',
        'label': 'Has Version',
        'item_key': 'dc-terms:hasVersion',
        'uri': 'http://purl.org/dc/terms/hasVersion',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_IS_PART_OF_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-is-part-of',
        'label': 'Is Part Of',
        'item_key': 'dc-terms:isPartOf',
        'uri': 'http://purl.org/dc/terms/isPartOf',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_IS_REFERENCED_BY_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-is-referenced-by',
        'label': 'Is Referenced By',
        'item_key': 'dc-terms:isReferencedBy',
        'uri': 'http://purl.org/dc/terms/isReferencedBy',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_IS_REPLACED_BY_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-is-replaced-by',
        'label': 'Is Replaced By',
        'item_key': 'dc-terms:isReplacedBy',
        'uri': 'http://purl.org/dc/terms/isReplacedBy',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_IS_VERSION_OF_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-is-version-of',
        'label': 'Is Version Of',
        'item_key': 'dc-terms:isVersionOf',
        'uri': 'http://purl.org/dc/terms/isVersionOf',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_LANGUAGE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-language',
        'label': 'Language',
        'item_key': 'dc-terms:language',
        'uri': 'http://purl.org/dc/terms/language',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_LICENSE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-license',
        'label': 'License',
        'item_key': 'dc-terms:license',
        'uri': 'http://purl.org/dc/terms/license',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_PUBLISHER_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-publisher',
        'label': 'Publisher',
        'item_key': 'dc-terms:publisher',
        'uri': 'http://purl.org/dc/terms/publisher',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_REFERENCES_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-references',
        'label': 'References',
        'item_key': 'dc-terms:references',
        'uri': 'http://purl.org/dc/terms/references',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_RELATION_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-relation',
        'label': 'Relation',
        'item_key': 'dc-terms:relation',
        'uri': 'http://purl.org/dc/terms/relation',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_REPLACES_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-replaces',
        'label': 'Replaces',
        'item_key': 'dc-terms:replaces',
        'uri': 'http://purl.org/dc/terms/replaces',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_SOURCE_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-source',
        'label': 'Source',
        'item_key': 'dc-terms:source',
        'uri': 'http://purl.org/dc/terms/source',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_SPATIAL_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-spatial',
        'label': 'Spatial Coverage',
        'item_key': 'dc-terms:spatial',
        'uri': 'http://purl.org/dc/terms/spatial',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_SUBJECT_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-subject',
        'label': 'Subject',
        'item_key': 'dc-terms:subject',
        'uri': 'http://purl.org/dc/terms/subject',
        'context_id': DCTERMS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_DCTERMS_TEMPORAL_UUID,
        'publisher_id': DCMI_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'dc-terms-temporal',
        'label': 'Temporal Coverage',
        'item_key': 'dc-terms:temporal',
        'uri': 'http://purl.org/dc/terms/temporal',
        'context_id': DCTERMS_VOCAB_UUID,
    },

    # Widely used Linked Data properties (SKOS)
    {
        'uuid': PREDICATE_SKOS_EXACT_MATCH_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-exact-match',
        'label': 'Has exact match',
        'item_key': 'skos:exactMatch',
        'uri': 'http://www.w3.org/2004/02/skos/core#exactMatch',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_CLOSE_MATCH_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-close-match',
        'label': 'Has close match',
        'item_key': 'skos:closeMatch',
        'uri': 'http://www.w3.org/2004/02/skos/core#closeMatch',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_NARROW_MATCH_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-narrower-match',
        'label': 'Has narrower match',
        'item_key': 'skos:narrowMatch',
        'uri': 'http://www.w3.org/2004/02/skos/core#narrowMatch',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_NARROWER_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-narrower',
        'label': 'Has narrower',
        'item_key': 'skos:narrower',
        'uri': 'http://www.w3.org/2004/02/skos/core#narrower',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_NARROWER_TRANS_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-narrower-transitive',
        'label': 'Has narrower transitive',
        'item_key': 'skos:narrowerTransitive',
        'uri': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_BROADER_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-broader',
        'label': 'Has broader',
        'item_key': 'skos:broader',
        'uri': 'http://www.w3.org/2004/02/skos/core#broader',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_BROADER_TRANS_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-broader-transitive',
        'label': 'Has broader transitive',
        'item_key': 'skos:broaderTransitive',
        'uri': 'http://www.w3.org/2004/02/skos/core#broaderTransitive',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_BROAD_MATCH_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-broad-match',
        'label': 'Has broader match',
        'item_key': 'skos:broadMatch',
        'uri': 'http://www.w3.org/2004/02/skos/core#broadMatch',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_RELATED_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-related',
        'label': 'Related',
        'item_key': 'skos:related',
        'uri': 'http://www.w3.org/2004/02/skos/core#related',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_EXAMPLE_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'skos-example',
        'label': 'Example',
        'item_key': 'skos:example',
        'uri': 'http://www.w3.org/2004/02/skos/core#example',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_PREFLABEL_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'skos-pref-label',
        'label': 'Preferred label',
        'item_key': 'skos:prefLabel',
        'uri': 'http://www.w3.org/2004/02/skos/core#prefLabel',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_ALTLABEL_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'skos-alt-label',
        'label': 'Alternative label',
        'item_key': 'skos:altLabel',
        'uri': 'http://www.w3.org/2004/02/skos/core#altLabel',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_DEFINITION_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'skos-definition',
        'label': 'Definition',
        'item_key': 'skos:definition',
        'uri': 'http://www.w3.org/2004/02/skos/core#definition',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_EDITORIAL_NOTE_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'skos-editorial-note',
        'label': 'Editorial Note',
        'item_key': 'skos:editorialNote',
        'uri': 'http://www.w3.org/2004/02/skos/core#editorialNote',
        'context_id': SKOS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_SKOS_NOTE_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'xsd:string',
        'slug': 'skos-note',
        'label': 'Note',
        'item_key': 'skos:note',
        'uri': 'http://www.w3.org/2004/02/skos/core#note',
        'context_id': SKOS_VOCAB_UUID,
    },
    # Widely used Linked Data properties (OWL)
    {
        'uuid': PREDICATE_OWL_CLASS_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'owl-class',
        'label': 'Class',
        'item_key': 'owl:Class',
        'uri': 'http://www.w3.org/2002/07/owl#Class',
        'context_id': OWL_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_OWL_ANNOTATION_PROPERTY_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'owl-annotation-property',
        'label': 'Annotation Property',
        'item_key': 'owl:AnnotationProperty',
        'uri': 'http://www.w3.org/2002/07/owl#AnnotationProperty',
        'context_id': OWL_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_OWL_OBJECT_PROPERTY_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'owl-object-property',
        'label': 'Object Property',
        'item_key': 'owl:ObjectProperty',
        'uri': 'http://www.w3.org/2002/07/owl#ObjectProperty',
        'context_id': OWL_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_OWL_SAME_AS_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'owl-same-as',
        'label': 'Same as',
        'item_key': 'owl:sameAs',
        'uri': 'http://www.w3.org/2002/07/owl#sameAs',
        'context_id': OWL_VOCAB_UUID,
    },
    # Widely used Linked Data properties (RDF)
    {
        'uuid': PREDICATE_RDF_TYPE_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdf-type',
        'label': 'Type of',
        'item_key': 'rdf:type',
        'uri': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
        'context_id': RDF_VOCAB_UUID,
    },
    # Widely used Linked Data properties (RDFS)
    {
        'uuid': PREDICATE_RDFS_SUB_CLASS_OF_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-sub-class-of',
        'label': 'Sub-class of',
        'item_key': 'rdfs:subClassOf',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#subClassOf',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_SUB_PROP_OF_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-sub-property-of',
        'label': 'Sub-property of',
        'item_key': 'rdfs:subPropertyOf',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#subPropertyOf',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_IS_DEFINED_BY_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-is-defined-by',
        'label': 'Is defined by',
        'item_key': 'rdfs:isDefinedBy',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#isDefinedBy',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_RANGE_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-range',
        'label': 'Has range',
        'item_key': 'rdfs:range',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#range',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_DOMAIN_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-domain',
        'label': 'Has domain',
        'item_key': 'rdfs:domain',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#domain',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_COMMENT_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-comment',
        'label': 'Has comment',
        'item_key': 'rdfs:comment',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#comment',
        'context_id': RDFS_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_RDFS_SEE_ALSO_UUID,
        'publisher_id': W3C_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'rdfs-see-also',
        'label': 'See also',
        'item_key': 'rdfs:seeAlso',
        'uri': 'https://www.w3.org/2000/01/rdf-schema#seeAlso',
        'context_id': RDFS_VOCAB_UUID,
    },
    # Creative Commons publisher and vocabularies
    {
        'uuid': CC_PUB_UUID,
        'publisher_id':CC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'cc-org',
        'label': 'Creative Commons',
        'uri': 'creativecommons.org',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': CC_LICENSE_VOCAB_UUID,
        'publisher_id': CC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'cc-licenses',
        'label': 'Creative Commons Licenses',
        'uri': 'creativecommons.org/licenses',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': CC_PUBLIC_DOMAIN_VOCAB_UUID,
        'publisher_id': CC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'cc-public-domain-dedications',
        'label': 'Creative Commons Pubic Domain Dedications',
        'uri': 'creativecommons.org/publicdomain',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': CC_DEFAULT_LICENSE_CC_BY_UUID,
        'publisher_id': CC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'uri',
        'data_type': 'id',
        'slug': 'cc-by-4',
        'label': 'Attribution 4.0 International (CC BY 4.0)',
        'uri': 'https://creativecommons.org/licenses/by/4.0/',
        'context_id': CC_LICENSE_VOCAB_UUID,
    },
    # FOAF publisher, vocabulary, classes and properties
    {
        'uuid': FOAF_PUB_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'foaf-project',
        'label': 'Friend of a Friend (FOAF)',
        'uri': 'www.foaf-project.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': FOAF_VOCAB_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'foaf-vocab',
        'label': 'Friend of a Friend (FOAF) Vocabulary',
        'uri': 'xmlns.com/foaf/spec',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': CLASS_FOAF_AGENT_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'foaf-agent',
        'label': 'Agent',
        'uri': 'http://xmlns.com/foaf/spec/#term_Agent',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': CLASS_FOAF_GROUP_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'foaf-group',
        'label': 'Group',
        'uri': 'http://xmlns.com/foaf/spec/#term_Group',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': CLASS_FOAF_PERSON_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'foaf-person',
        'label': 'Person',
        'uri': 'http://xmlns.com/foaf/spec/#term_Person',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': CLASS_FOAF_ORGANIZATION_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'foaf-organization',
        'label': 'Organization',
        'uri': 'http://xmlns.com/foaf/spec/#term_Organization',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': CLASS_FOAF_IMAGE_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'class',
        'data_type': 'id',
        'slug': 'foaf-image',
        'label': 'Image',
        'uri': 'http://xmlns.com/foaf/spec/#term_Image',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_FOAF_IMG_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'foaf-prop-image',
        'label': 'Has image',
        'uri': 'http://xmlns.com/foaf/spec/#term_img',
        'context_id': FOAF_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_FOAF_PRIMARY_TOPIC_OF_UUID,
        'publisher_id': FOAF_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'foaf-primary-topic-of',
        'label': 'Is primary topic of',
        'uri': 'http://xmlns.com/foaf/spec/#term_isPrimaryTopicOf',
        'context_id': FOAF_VOCAB_UUID,
    },
    # DBPEDIA Publisher and Vocabulary
    {
        'uuid': DBPEDIA_PUB_UUID,
        'publisher_id': DBPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'dbpedia-org',
        'label': 'DBpedia Association',
        'uri': 'https://wiki.dbpedia.org/membership',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': DBPEDIA_VOCAB_UUID,
        'publisher_id': DBPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'dbpedia-vocab',
        'label': 'DBpedia',
        'uri': 'dbpedia.org',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # ORCID Publisher and Vocabulary
    {
        'uuid': ORCID_PUB_UUID,
        'publisher_id': ORCID_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'orcid-org',
        'label': 'ORCID - Organization',
        'uri': 'https://orcid.org/about',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': ORCID_VOCAB_UUID,
        'publisher_id': ORCID_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'orcid-vocab',
        'label': 'ORCID',
        'uri': 'orcid.org',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # Bibo (Bibliographic ontology)
    {
        'uuid': BIBO_PUB_UUID,
        'publisher_id': BIBO_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'bibo-community',
        'label': 'Bibliographic Ontology Community',
        'uri': 'http://www.bibliontology.com/community.html',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': BIBO_VOCAB_UUID,
        'publisher_id': BIBO_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'bibo-ontology',
        'label': 'Bibliographic Ontology',
        'uri': 'http://www.bibliontology.com/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # CIDOC-CRM Ontology, publisher, and predicates
    {
        'uuid': CIDOC_PUB_UUID,
        'publisher_id': CIDOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'cidoc-icon',
        'label': 'International Committee for Documentation (ICOM)',
        'uri': 'http://cidoc.mini.icom.museum/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': CIDOC_VOCAB_UUID,
        'publisher_id': CIDOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'cidoc-crm',
        'label': 'CIDOC Conceptual Reference Model (CRM)',
        'uri': 'http://www.cidoc-crm.org/cidoc-crm/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': PREDICATE_CIDOC_CONSISTS_OF_UUID,
        'publisher_id': CIDOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'cidoc-crm-p45-consists-of',
        'label': 'Consists of',
        'uri': 'http://erlangen-crm.org/current/P45_consists_of',
        'context_id': CIDOC_VOCAB_UUID,
    },
    {
        'uuid': PREDICATE_CIDOC_HAS_TYPE_UUID,
        'publisher_id': CIDOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'property',
        'data_type': 'id',
        'slug': 'cidoc-crm-p2-has-type',
        'label': 'Has type',
        'uri': 'http://erlangen-crm.org/current/P2_has_type',
        'context_id': CIDOC_VOCAB_UUID,
    },
    # GeoJSON - LD
    {
        'uuid': GEOJSON_PUB_UUID,
        'publisher_id': GEOJSON_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'geojson-org',
        'label': 'Geographic JSON (geojson) Working Group and Collaborators',
        'uri': 'https://geojson.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': GEOJSON_VOCAB_UUID,
        'publisher_id': GEOJSON_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'geojson-ld',
        'label': 'GeoJSON-LD',
        'uri': 'https://geojson.org/geojson-ld/geojson-context.jsonld',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # Library of Congress
    {
        'uuid': LOC_PUB_UUID,
        'publisher_id': LOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'loc-gov',
        'label': 'Library of Congress',
        'uri': 'https://loc.gov/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': LOC_SUBJ_HEAD_VOCAB_UUID,
        'publisher_id': LOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'loc-sh',
        'label': 'Library of Congress Subject Headings',
        'uri': 'http://id.loc.gov/authorities/subjects',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': LOC_PERIODO_VOCAB_UUID,
        'publisher_id': LOC_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'loc-p0-sh',
        'label': 'PeriodO: Library of Congress Subject Headings',
        'uri': 'http://n2t.net/ark:/99152/p06c6g3',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # Getty
    {
        'uuid': GETTY_PUB_UUID,
        'publisher_id': GETTY_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'getty-inst',
        'label': 'Getty Research Institute',
        'uri': 'https://www.getty.edu/research/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': GETTY_AAT_VOCAB_UUID,
        'publisher_id': GETTY_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'getty-aat',
        'label': 'Getty Art and Architecture Thesaurus',
        'uri': 'http://vocab.getty.edu/aat/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # Wikipedia Publisher and Vocabulary
    {
        'uuid': WIKIPEDIA_PUB_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'publishers',
        'data_type': 'id',
        'slug': 'wikimedia-foundation',
        'label': 'Wikimedia Foundation',
        'uri': 'https://wikimediafoundation.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': WIKIPEDIA_VOCAB_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'wikipedia',
        'label': 'Wikipedia: The Free Encyclopedia',
        'uri': 'www.wikipedia.org',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': WIKIDATA_VOCAB_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'wikidata',
        'label': 'Wikidata',
        'uri': 'www.wikidata.org/',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    {
        'uuid': WIKTIONARY_VOCAB_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'vocabularies',
        'data_type': 'id',
        'slug': 'wiktionary-en',
        'label': 'English-language Wiktionary',
        'uri': 'en.wiktionary.org',
        'context_id': OPEN_CONTEXT_PROJ_UUID,
    },
    # Add a bunch of languages with Wikidata URIs
    # We're using Wikidata URIs because they seem the most useful.
    {
        'uuid': LANG_AR_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-arabic',
        'label': 'Arabic',
        'uri': 'https://www.wikidata.org/wiki/Q13955',
        'item_key': 'ar',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'العَرَبِية',
            'script_code': 'ar',
            'iso_639_3_code': 'ara',
        }
    },
    {
        'uuid': LANG_DE_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-german',
        'label': 'German',
        'uri': 'https://www.wikidata.org/wiki/Q188',
        'item_key': 'de',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'Deutsch',
            'script_code': 'la',
            'iso_639_3_code': 'deu',
        }
    },
    {
        'uuid': LANG_EL_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-greek',
        'label': 'Greek',
        'uri': 'https://www.wikidata.org/wiki/Q9129',
        'item_key': 'el',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'ελληνικά',
            'script_code': 'el',
            'iso_639_3_code': 'ell',
        }
    },
    {
        'uuid': LANG_EN_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-english',
        'label': 'English',
        'uri': 'https://www.wikidata.org/wiki/Q1860',
        'item_key': 'en',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'English',
            'script_code': 'la',
            'iso_639_3_code': 'eng',
        }
    },
    {
        'uuid': LANG_ES_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-spanish',
        'label': 'Spanish',
        'uri': 'https://www.wikidata.org/wiki/Q1321',
        'item_key': 'es',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'Español',
            'script_code': 'la',
            'iso_639_3_code': 'spa',
        }
    },
    {
        'uuid': LANG_FA_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-persian',
        'label': 'Persian',
        'uri': 'https://www.wikidata.org/wiki/Q9168',
        'item_key': 'fa',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'فارسی',
            'script_code': 'ar',
            'iso_639_3_code': 'fas',
        }
    },
    {
        'uuid': LANG_FR_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-french',
        'label': 'French',
        'uri': 'https://www.wikidata.org/wiki/Q150',
        'item_key': 'fr',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'Français',
            'script_code': 'la',
            'iso_639_3_code': 'fra',
        }
    },
    {
        'uuid': LANG_HE_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-hebrew',
        'label': 'Hebrew',
        'uri': 'https://www.wikidata.org/wiki/Q9288',
        'item_key': 'he',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'עברית',
            'script_code': 'he',
            'iso_639_3_code': 'heb',
        }
    },
    {
        'uuid': LANG_IT_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-italian',
        'label': 'Italian',
        'uri': 'https://www.wikidata.org/wiki/Q652',
        'item_key': 'it',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'Italiano',
            'script_code': 'la',
            'iso_639_3_code': 'ita',
        }
    },
    {
        'uuid': LANG_TR_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-turkish',
        'label': 'Turkish',
        'uri': 'https://www.wikidata.org/wiki/Q256',
        'item_key': 'tr',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': 'Türkçe',
            'script_code': 'la',
            'iso_639_3_code': 'tur',
        }
    },
    {
        'uuid': LANG_ZH_UUID,
        'publisher_id': WIKIPEDIA_PUB_UUID,
        'project_id': OPEN_CONTEXT_PROJ_UUID,
        'item_class_id': DEFAULT_CLASS_UUID,
        'source_id': DEFAULT_SOURCE_ID,
        'item_type': 'languages',
        'data_type': 'id',
        'slug': 'lang-chinese',
        'label': 'Chinese',
        'uri': 'https://www.wikidata.org/wiki/Q7850',
        'item_key': 'zh',
        'context_id': WIKIDATA_VOCAB_UUID,
        'meta_json': {
            'label_localized': '中文',
            'script_code': 'la',
            'iso_639_3_code': 'zho',
        }
    },
]


def is_valid_uuid(val):
    try:
        return GenUUID.UUID(str(val))
    except ValueError:
        return None


def verify_manifest_uuids(dict_list=DEFAULT_MANIFESTS):
    """Verifies deterministically created uuids"""
    check_types = (
        URI_CONTEXT_PREFIX_ITEM_TYPES
        + ['vocabularies']
    )
    for man_dict in dict_list:
        uuid = man_dict['uuid']
        uri = man_dict['uri']
        if man_dict['item_type'] not in check_types:
            # Not an item type that has a 
            # deterministic uuid
            continue
        ex_uuid = AllManifest().primary_key_create(
            item_type=man_dict['item_type'],
            project_id=man_dict['project_id'],
            context_id=man_dict['context_id'],
            uri=uri,
        )
        if not is_valid_uuid(uuid):
            raise ValueError(f'Not a valid config uuid: {uuid}')
        if not is_valid_uuid(ex_uuid):
            raise ValueError(f'Not a valid geerated uuid: {ex_uuid}')
        if ex_uuid == uuid:
            continue
        print(f'{uri} should have {ex_uuid}')


def load_default_entities(
    man_dict_list=DEFAULT_MANIFESTS,
    str_dict_list=DEFAULT_STRINGS
    ):
    """Loads default, required by Open Context """
    fk_fields = [
        'publisher_id', 
        'project_id', 
        'item_class_id', 
        'context_id'
    ]
    for man_dict in man_dict_list:
        uuid = man_dict['uuid']
        if not is_valid_uuid(uuid):
            raise ValueError(f'Not a valid config uuid: {uuid}')
        m, _ = AllManifest.objects.get_or_create(
            uuid=uuid,
            defaults=man_dict
        )
        print(f'Item {m.uuid}, {m.label} created.')
    
    for man_dict in man_dict_list:
        uuid = man_dict['uuid']
        m = AllManifest.objects.get(uuid=uuid)
        for fk_field in fk_fields:
            fk_val = man_dict.get(fk_field)
            if not fk_val:
                # This foreign key field is not set
                continue
            setattr(m, fk_field, fk_val)

        print(f'Updating related for {m.label}')
        m.save()
    
    for str_dict in str_dict_list:
        uuid = str_dict['uuid']
        if not is_valid_uuid(uuid):
            raise ValueError(f'Not a valid config uuid: {uuid}')
        str_obj, _ = AllString.objects.get_or_create(
            uuid=uuid,
            defaults=str_dict
        )
        print(
            f'String obj {str_obj.uuid}, "{str_obj.content}" created.'
        )
        