
DEFAULT_LICENSE_ICONS = {
    'creativecommons.org/licenses/by/': '../../static/oc/cc-icons/cc-by.svg',
    'creativecommons.org/licenses/by-nc/': '../../static/oc/cc-icons/cc-by-nc.svg',
    'creativecommons.org/licenses/by-nc-nd/': '../../static/oc/cc-icons/cc-by-nc-nd.svg',
    'creativecommons.org/licenses/by-nc-sa/': '../../static/oc/cc-icons/cc-by-nc-sa.svg',
    'creativecommons.org/licenses/by-nd/': '../../static/oc/cc-icons/cc-by-nd.svg',
    'creativecommons.org/licenses/by-sa/': '../../static/oc/cc-icons/cc-by-sa.svg',
    'creativecommons.org/publicdomain/mark/': '../../static/oc/cc-icons/cc-publicdomain.svg',
    'creativecommons.org/publicdomain/zero/': '../../static/oc/cc-icons/cc-zero.svg',
}


DEFAULT_ITEM_TYPE_ICONS = {
    'attribute-groups': '../../static/oc/icons-v2/noun-attribute-group-analysis-4808151.svg',
    'class': '../../static/oc/icons-v2/noun-tree-diagram-152829.svg',
    'documents': '../../static/oc/icons-v2/noun-document-3183378.svg',
    'events': '../../static/oc/icons-v2/noun-event-address-book-timing-997565.svg',
    'languages': '../../static/oc/icons-v2/noun-language-3091153.svg',
    'media': '../../static/oc/icons-v2/noun-format-3644407.svg',
    'media-types': '../../static/oc/icons-v2/noun-format-3631540.svg',
    'observations': '../../static/oc/icons-v2/noun-clipboard-147519.svg',
    'persons': '../../static/oc/icons-v2/noun-people-3393687.svg',
    'predicates': '../../static/oc/icons-v2/noun-attribute-4326168.svg',
    'projects': '../../static/oc/icons-v2/noun-research-project-2341022.svg',
    'property': '../../static/oc/icons-v2/noun-rdf-3855711.svg',
    'publishers': '../../static/oc/icons-v2/noun-offset-printing-3313820.svg',
    # 'subjects': '../../static/oc/icons-v2/noun-object-3504999.svg',
    # 'subjects_children': '../../static/oc/icons-v2/noun-object-3504999.svg',
    'subjects': '../../static/oc/icons-v2/noun-locally-made-compost-4476027.svg',
    'subjects_children': '../../static/oc/icons-v2/noun-inclusive-410851.svg',
    'tables': '../../static/oc/icons-v2/noun-table-4305.svg',
    'types': '../../static/oc/icons-v2/noun-classification-4487097.svg',
    'units': '../../static/oc/icons-v2/noun-size-2931148.svg',
    'uri': '../../static/oc/icons-v2/noun-website-88991.svg',
    'vocabularies': '../../static/oc/icons-v2/noun-document-shared-821182',
}


ITEM_TYPE_CLASS_ICONS_DICT = {
    "attribute-groups": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class"
        }
    ],
    "class": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class"
        },
    ],
    "documents": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
        }
    ],
    "events": [
        {
            "item_class__uuid": "00000000-6e24-06a3-7098-a0dc01915ff6",
            "item_class__label": "Geographic Coverage",
            "item_class__item_key": "oc-gen:geo-coverage",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/geo-coverage",
            "item_class__slug": "oc-gen-geo-coverage",
            "icon": "../../static/oc/icons-v2/noun-map-multi-pin-3529412.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-336d-3531-54f40f2dcce0",
            "item_class__label": "General time and location",
            "item_class__item_key": "oc-gen:general-time-space",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/general-time-space",
            "item_class__slug": "oc-gen-general-time-space",
            "icon": "../../static/oc/icons-v2/noun-event-location-4512308.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-d923-4de9-195609a19040",
            "item_class__label": "Origins time and location",
            "item_class__item_key": "oc-gen:origins-time-location",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/origins-time-location",
            "item_class__slug": "oc-gen-origins-time-location",
            "icon": "../../static/oc/icons-v2/noun-origin-address-2370172.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-eb5e-0cca-1ac8dc56c571",
            "item_class__label": "(More) current location",
            "item_class__item_key": "oc-gen:current-location",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/current-location",
            "item_class__slug": "oc-gen-current-location",
            "icon": "../../static/oc/icons-v2/noun-current-location-1387599.svg",
        }
    ],
    "languages": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-language-3091153.svg",
        }
    ],
    "media": [
        {
            "item_class__uuid": "00000000-6e24-450b-f31d-a40eb0eb17a4",
            "item_class__label": "Document media",
            "item_class__item_key": "oc-gen:document-file",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/document-file",
            "item_class__slug": "oc-gen-document-file",
            "icon": "../../static/oc/icons-v2/noun-file-and-document-905136.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-7e2d-cc5b-f6ef63cf0398",
            "item_class__label": "Vector geospatial (GIS) media",
            "item_class__item_key": "oc-gen:gis-vector-file",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/gis-vector-file",
            "item_class__slug": "oc-gen-gis-vector-file",
            "icon": "../../static/oc/icons-v2/noun-gis-14294.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-dcc6-6bba-9fda0020066d",
            "item_class__label": "Image media",
            "item_class__item_key": "oc-gen:image",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/image",
            "item_class__slug": "oc-gen-image",
            "icon": "../../static/oc/icons-v2/noun-image-file-1453705.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-e162-4d23-95a790a799fd",
            "item_class__label": "3D media",
            "item_class__item_key": "oc-gen:3d-model",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/3d-model",
            "item_class__slug": "oc-gen-3d-model",
            "icon": "../../static/oc/icons-v2/noun-3d-model-file-966229.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-e1e8-f0fe-e12bf8ac884f",
            "item_class__label": "Tabular data media",
            "item_class__item_key": "oc-gen:data-table",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/data-table",
            "item_class__slug": "oc-gen-data-table",
            "icon": "../../static/oc/icons-v2/noun-data-file-1898055.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-86f1-36cd-8cad34f70b6b",
            "item_class__label": "Video media",
            "item_class__item_key": "oc-gen:video",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/video",
            "item_class__slug": "oc-gen-video",
            "icon": "../../static/oc/icons-v2/noun-video-file-890154.svg",
        },
    ],
    "media-types": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-media-types-format-3644407.svg",
        },
    ],
    "observations": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            # see also: noun-observations-research-3325851.svg
            "icon": "../../static/oc/icons-v2/noun-observations-research-4824813.svg",
        },
    ],
    "persons": [
        {
            "item_class__uuid": "00000000-546a-df1c-0e55-4f27d6cbe824",
            "item_class__label": "Organization",
            "item_class__item_key": None,
            "item_class__uri": "xmlns.com/foaf/spec/#term_Organization",
            "item_class__slug": "foaf-organization",
            "icon": "../../static/oc/icons-v2/noun-collaboration-4669519.svg",
        },
        {
            "item_class__uuid": "00000000-546a-e6c7-7c0a-2909e60e7c81",
            "item_class__label": "Person",
            "item_class__item_key": None,
            "item_class__uri": "xmlns.com/foaf/spec/#term_Person",
            "item_class__slug": "foaf-person",
            "icon": "../../static/oc/icons-v2/noun-people-3393687.svg",
        },
    ],
    "predicates": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-predicates-attributes-4562668.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-4637-cc82-fb0add3bb01b",
            "item_class__label": "Variables",
            "item_class__item_key": "oc-gen:variables",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/variables",
            "item_class__slug": "oc-gen-variables",
            "icon": "../../static/oc/icons-v2/noun-summary-495517.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-5e11-6d91-b097262f3f05",
            "item_class__label": "Links",
            "item_class__item_key": "oc-gen:links",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/links",
            "item_class__slug": "oc-gen-pred-links",
            "icon": "../../static/oc/icons-v2/noun-network-614248.svg",
        },
    ],
    "projects": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-research-project-2341022.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-956a-2395-8be4933d4d27",
            "item_class__label": "Collection",
            "item_class__item_key": "oc-gen:cat-collection",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-collection",
            "item_class__slug": "oc-gen-cat-collection",
            "icon": "../../static/oc/icons-v2/noun-archive-boxes-6666382.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-de9d-3040-a85d9f2cbc6d",
            "item_class__label": "Data Publication",
            "item_class__item_key": "oc-gen:cat-data-publication",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-data-publication",
            "item_class__slug": "oc-gen-cat-data-publication",
            "icon": "../../static/oc/icons-v2/noun-research-project-2341022.svg",
        },
    ],
    "property": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-predicates-attributes-4562668.svg",
        },
    ],
    "publishers": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-publishers-1275981.svg",
        },
    ],
    "subjects": [
        {
            "item_class__uuid": "00000000-6e24-03af-5931-5df0932d6be2",
            "item_class__label": "Feature",
            "item_class__item_key": "oc-gen:cat-feature",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-feature",
            "item_class__slug": "oc-gen-cat-feature",
            "icon": "../../static/oc/icons-v2/noun-trowl-foundation-4804020.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-b278-5945-bc7a0fd3c20c",
            "item_class__label": "Radiocarbon Sample",
            "item_class__item_key": "oc-gen:cat-c14-sample",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-c14-sample",
            "item_class__slug": "oc-gen-cat-c14-sample",
            "icon": "../../static/oc/icons-v2/noun-atomic-6823535.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-0b70-0230-0cc0398d6184",
            "item_class__label": "Sample",
            "item_class__item_key": "oc-gen:cat-sample",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-sample",
            "item_class__slug": "oc-gen-cat-sample",
            "icon": "../../static/oc/icons-v2/noun-sample-4489840.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-1147-b189-ad24b8a86f76",
            "item_class__label": "Sample, Collection, or Aggregation",
            "item_class__item_key": "oc-gen:cat-sample-col",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-sample-col",
            "item_class__slug": "oc-gen-cat-sample-col",
            "icon": "../../static/oc/icons-v2/noun-boxes-381485.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-2339-9f63-582218c3f76a",
            "item_class__label": "Object",
            "item_class__item_key": "oc-gen:cat-object",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-object",
            "item_class__slug": "oc-gen-cat-object",
            "icon": "../../static/oc/icons-v2/object-icon-draft-2.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-4d0e-1464-87277c5d0173",
            "item_class__label": "Square",
            "item_class__item_key": "oc-gen:cat-square",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-square",
            "item_class__slug": "oc-gen-cat-square",
            "icon": "../../static/oc/icons-v2/noun-square-isometric-grid-northwest-4828972.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-5288-f1a5-0cb5f57b4475",
            "item_class__label": "Lot",
            "item_class__item_key": "oc-gen:cat-lot",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-lot",
            "item_class__slug": "oc-gen-cat-lot",
            "icon": "../../static/oc/icons-v2/oc-context-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-600d-a274-f02367a32c33",
            "item_class__label": "Locus",
            "item_class__item_key": "oc-gen:cat-locus",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-locus",
            "item_class__slug": "oc-gen-cat-locus",
            "icon": "../../static/oc/icons-v2/oc-context-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-65d0-e0e4-27fa67c62929",
            "item_class__label": "Pottery",
            "item_class__item_key": "oc-gen:cat-pottery",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-pottery",
            "item_class__slug": "oc-gen-cat-pottery",
            "icon": "../../static/oc/icons-v2/noun-pottery-2956136.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-71d3-33f6-e29baa1e5c47",
            "item_class__label": "Area",
            "item_class__item_key": "oc-gen:cat-area",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-area",
            "item_class__slug": "oc-gen-cat-area",
            "icon": "../../static/oc/icons-v2/noun-area-ground-1283937.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-73a2-bb4a-2e9334cda77c",
            "item_class__label": "Plant remains",
            "item_class__item_key": "oc-gen:cat-plant-remains",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-plant-remains",
            "item_class__slug": "oc-gen-cat-plant-remains",
            "icon": "../../static/oc/icons-v2/noun-seeds-39425.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-79df-155f-ff1972774d88",
            "item_class__label": "Operation",
            "item_class__item_key": "oc-gen:cat-operation",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-operation",
            "item_class__slug": "oc-gen-cat-operation",
        },
        {
            "item_class__uuid": "00000000-6e24-7c9f-b487-e9973c6da06d",
            "item_class__label": "Biological Record",
            "item_class__item_key": "oc-gen:cat-bio-subj-ecofact",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-bio-subj-ecofact",
            "item_class__slug": "oc-gen-cat-bio-subj-ecofact",
            "icon": "../../static/oc/icons-v2/noun-integrated-crop-livestock-4475829.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-885e-0dd2-c30a4228b7d3",
            "item_class__label": "Human Bone",
            "item_class__item_key": "oc-gen:cat-human-bone",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-human-bone",
            "item_class__slug": "oc-gen-cat-human-bone",
            "icon": "../../static/oc/icons-v2/noun-skull-84955.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-8999-1c4e-817d853f967a",
            "item_class__label": "Coin",
            "item_class__item_key": "oc-gen:cat-coin",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-coin",
            "item_class__slug": "oc-gen-cat-coin",
            "icon": "../../static/oc/icons-v2/noun-coin-501476.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-9594-57e4-744439eb8fac",
            "item_class__label": "Sculpture",
            "item_class__item_key": "oc-gen:cat-sculpture",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-sculpture",
            "item_class__slug": "oc-gen-cat-sculpture",
            "icon": "../../static/oc/icons-v2/noun-monument-display-2824289.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-987f-cf3f-854feaa7b768",
            "item_class__label": "Reference Collection",
            "item_class__item_key": "oc-gen:cat-ref-col",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-ref-col",
            "item_class__slug": "oc-gen-cat-ref-col",
            "icon": "../../static/oc/icons-v2/noun-ref-collection-inventory-4022838.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-9eed-7071-53ba4dfbec32",
            "item_class__label": "Phase",
            "item_class__item_key": "oc-gen:cat-phase",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-phase",
            "item_class__slug": "oc-gen-cat-phase",
            "icon": "../../static/oc/icons-v2/phase-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-9f21-7326-d09207d65387",
            "item_class__label": "Architectural Element",
            "item_class__item_key": "oc-gen:cat-arch-element",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-arch-element",
            "item_class__slug": "oc-gen-cat-arch-element",
            "icon": "../../static/oc/icons-v2/noun-architecture-column-3507450.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-a029-1e7b-9879507510af",
            "item_class__label": "Survey Unit",
            "item_class__item_key": "oc-gen:cat-survey-unit",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-survey-unit",
            "item_class__slug": "oc-gen-cat-survey-unit"
        },
        {
            "item_class__uuid": "00000000-6e24-a96d-ee27-e62f88724381",
            "item_class__label": "Site",
            "item_class__item_key": "oc-gen:cat-site",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-site",
            "item_class__slug": "oc-gen-cat-site",
            "icon": "../../static/oc/icons-v2/noun-trowel-3586734.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-b435-800b-f7a82361295f",
            "item_class__label": "Trench",
            "item_class__item_key": "oc-gen:cat-trench",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-trench",
            "item_class__slug": "oc-gen-cat-trench",
            "icon": "../../static/oc/icons-v2/oc-trench-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-c7f5-a746-2ec91b5f1825",
            "item_class__label": "Structure",
            "item_class__item_key": "oc-gen:cat-structure",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-structure",
            "item_class__slug": "oc-gen-cat-structure",
            "icon": "../../static/oc/icons-v2/noun-columns-4438180.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-c97b-e4e6-b74475cc4ba7",
            "item_class__label": "Excavation Unit",
            "item_class__item_key": "oc-gen:cat-exc-unit",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-exc-unit",
            "item_class__slug": "oc-gen-cat-exc-unit",
            "icon": "../../static/oc/icons-v2/oc-context-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-d0cd-df8d-4dbb6c2bd1dd",
            "item_class__label": "Glass",
            "item_class__item_key": "oc-gen:cat-glass",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-glass",
            "item_class__slug": "oc-gen-cat-glass",
            "icon": "../../static/oc/icons-v2/noun-glass-bottle-4152315.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-d81b-3d32-07ed62bbaab1",
            "item_class__label": "Site Area",
            "item_class__item_key": "oc-gen:cat-site-area",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-site-area",
            "item_class__slug": "oc-gen-cat-site-area",
        },
        {
            "item_class__uuid": "00000000-6e24-dd34-5de6-11ed76e67c2e",
            "item_class__label": "Unit",
            "item_class__item_key": "oc-gen:cat-unit",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-unit",
            "item_class__slug": "oc-gen-cat-unit",
            "icon": "../../static/oc/icons-v2/oc-context-icon.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-e55c-6c25-5d7204d9115c",
            "item_class__label": "Region",
            "item_class__item_key": "oc-gen:cat-region",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-region",
            "item_class__slug": "oc-gen-cat-region",
            "icon": "../../static/oc/icons-v2/noun-region-3097495.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-f30b-8381-0e608046f9b5",
            "item_class__label": "Animal Bone",
            "item_class__item_key": "oc-gen:cat-animal-bone",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/cat-animal-bone",
            "item_class__slug": "oc-gen-cat-animal-bone",
            "icon": "../../static/oc/icons-v2/noun-camel-4109324.svg",
        },
        {
            "item_class__uuid": "00000000-6e24-d192-dee7-bbbbf881612b",
            "item_class__label": "Arbitrary Grouping",
            "item_class__item_key": "oc-gen:cat-arbitrary-grouping",
            "item_class__uri": "opencontext.org/vocabularies/oc-general/oc-gen-cat-arbitrary-grouping",
            "item_class__slug": "'oc-gen-cat-arbitrary-grouping",
            "icon": "../../static/oc/icons-v2/noun-particles-5777121.svg",
        },
    ],
    "tables": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-table-4305.svg",
        },
    ],
    "types": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-types-hierarchy-1535342.svg",
        },
    ],
    "units": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-units-ruler-and-pencil-892938.svg",
        },
    ],
    "uri": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-website-88991.svg",
        },
    ],
    "vocabularies": [
        {
            "item_class__uuid": "00000000-0000-0000-0000-000000000002",
            "item_class__label": "Default (null) class",
            "item_class__item_key": None,
            "item_class__uri": "opencontext.org/vocabularies/oc-general/default-class",
            "item_class__slug": "oc-default-class",
            "icon": "../../static/oc/icons-v2/noun-hierarchy-564708.svg",
        },
    ]
}

WORLD_REGION_ICONS = {
    'Africa': '../../static/oc/icons-v2/noun-africa-297982.svg',
    'Americas': '../../static/oc/icons-v2/noun-americas-829021.svg',
    'Asia': '../../static/oc/icons-v2/noun-asia-740449.svg',
    'Europe': '../../static/oc/icons-v2/noun-europe-178615.svg',
    'Off World': '../../static/oc/icons-v2/noun-solar-system-167829.svg',
    'Oceania': '../../static/oc/icons-v2/noun-pacific-411980.svg',
    'World': '../../static/oc/icons-v2/noun-earth-1867754.svg',
}