# Generated by Django 5.1 on 2024-08-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEstimate',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('session_id', models.TextField()),
                ('hash_id', models.TextField()),
                ('estimated_cost', models.FloatField(null=True)),
                ('input_json', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'oc_publish_estimates',
                'ordering': ['updated', 'session_id'],
                'unique_together': {('session_id', 'hash_id')},
            },
        ),
    ]
